In [1]:
import pandas as pd

In [61]:
import numpy as np

In [2]:
pd.__version__

'2.0.3'

In [44]:
housing_data = pd.read_csv("housing.csv")

In [45]:
housing_data.shape

(20640, 10)

In [46]:
housing_data.isnull().any()

longitude             False
latitude              False
housing_median_age    False
total_rooms           False
total_bedrooms         True
population            False
households            False
median_income         False
median_house_value    False
ocean_proximity       False
dtype: bool

In [52]:
# all unique values in ocean_proximity column
housing_data.ocean_proximity.unique()

# no of unique values
#housing_data.ocean_proximity.nunique()


array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [48]:
# average value of the median_house_value for the houses "NEAR BAY"
near_bay = housing_data[housing_data['ocean_proximity']=='NEAR BAY']
near_bay['median_house_value'].mean()

259212.31179039303

In [49]:
# average no of total_bedrooms when there are missing values in the data
avg_total_bedrooms = housing_data['total_bedrooms'].mean()
housing_data['total_bedrooms'].isnull().sum()
avg_total_bedrooms


537.8705525375618

In [50]:
housing_data.total_bedrooms.fillna(value=avg_total_bedrooms, axis=0, inplace=True)

housing_data['total_bedrooms'].isnull().sum()

0

In [51]:
housing_data['total_bedrooms'].mean()

537.8705525375617

In [88]:
island_housing = housing_data.loc[housing_data['ocean_proximity']=="ISLAND",['housing_median_age','total_rooms','total_bedrooms']]

# let's call it X
X = np.array(island_housing)
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [89]:
X.T

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [90]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [91]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [92]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [93]:
# matrix-matrix multiplication between transpose of X and X
XTX = matrix_matrix_multiplication(X.T,X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [94]:
# inverse of XTX
inverse_of_XTX = np.linalg.inv(XTX)
inverse_of_XTX

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [95]:
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [98]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
temp = matrix_matrix_multiplication(inverse_of_XTX, X.T)


w = matrix_vector_multiplication(temp, y)
w


array([23.12330961, -1.48124183,  5.69922946])